package org.hibernate.model;
// Generated 21/08/2012 05:48:10 PM by Hibernate Tools 3.2.1.GA



/**
 * Aeropuerto generated by hbm2java
 */
public class Aeropuerto  implements java.io.Serializable {


     private Integer idAeropuerto;
     private String nombre;
     private String ciudad;

    public Aeropuerto() {
    }

    public Aeropuerto(String nombre, String ciudad) {
       this.nombre = nombre;
       this.ciudad = ciudad;
    }
   
    public Integer getIdAeropuerto() {
        return this.idAeropuerto;
    }
    
    public void setIdAeropuerto(Integer idAeropuerto) {
        this.idAeropuerto = idAeropuerto;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getCiudad() {
        return this.ciudad;
    }
    
    public void setCiudad(String ciudad) {
        this.ciudad = ciudad;
    }




}


