package org.hibernate.model;
// Generated 21/08/2012 05:48:10 PM by Hibernate Tools 3.2.1.GA



/**
 * Avion generated by hbm2java
 */
public class Avion  implements java.io.Serializable {


     private Integer idAvion;
     private int capacidad;
     private int idReservacion;

    public Avion() {
    }

    public Avion(int capacidad, int idReservacion) {
       this.capacidad = capacidad;
       this.idReservacion = idReservacion;
    }
   
    public Integer getIdAvion() {
        return this.idAvion;
    }
    
    public void setIdAvion(Integer idAvion) {
        this.idAvion = idAvion;
    }
    public int getCapacidad() {
        return this.capacidad;
    }
    
    public void setCapacidad(int capacidad) {
        this.capacidad = capacidad;
    }
    public int getIdReservacion() {
        return this.idReservacion;
    }
    
    public void setIdReservacion(int idReservacion) {
        this.idReservacion = idReservacion;
    }




}


