package org.hibernate.model;
// Generated 21/08/2012 05:48:10 PM by Hibernate Tools 3.2.1.GA



/**
 * Clientes generated by hbm2java
 */
public class Clientes  implements java.io.Serializable {


     private Integer idCliente;
     private String nombre;
     private String APaterno;
     private String AMaterno;
     private String sexo;
     private int edad;
     private int cantidadDeNinos;
     private int cantidadDeAdultos;

    public Clientes() {
    }

    public Clientes(String nombre, String APaterno, String AMaterno, String sexo, int edad, int cantidadDeNinos, int cantidadDeAdultos) {
       this.nombre = nombre;
       this.APaterno = APaterno;
       this.AMaterno = AMaterno;
       this.sexo = sexo;
       this.edad = edad;
       this.cantidadDeNinos = cantidadDeNinos;
       this.cantidadDeAdultos = cantidadDeAdultos;
    }
   
    public Integer getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(Integer idCliente) {
        this.idCliente = idCliente;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getAPaterno() {
        return this.APaterno;
    }
    
    public void setAPaterno(String APaterno) {
        this.APaterno = APaterno;
    }
    public String getAMaterno() {
        return this.AMaterno;
    }
    
    public void setAMaterno(String AMaterno) {
        this.AMaterno = AMaterno;
    }
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }
    public int getEdad() {
        return this.edad;
    }
    
    public void setEdad(int edad) {
        this.edad = edad;
    }
    public int getCantidadDeNinos() {
        return this.cantidadDeNinos;
    }
    
    public void setCantidadDeNinos(int cantidadDeNinos) {
        this.cantidadDeNinos = cantidadDeNinos;
    }
    public int getCantidadDeAdultos() {
        return this.cantidadDeAdultos;
    }
    
    public void setCantidadDeAdultos(int cantidadDeAdultos) {
        this.cantidadDeAdultos = cantidadDeAdultos;
    }




}


