package org.hibernate.model;
// Generated 21/08/2012 05:48:10 PM by Hibernate Tools 3.2.1.GA



/**
 * Reservaciones generated by hbm2java
 */
public class Reservaciones  implements java.io.Serializable {


     private Integer idReservacion;
     private int idCliente;

    public Reservaciones() {
    }

    public Reservaciones(int idCliente) {
       this.idCliente = idCliente;
    }
   
    public Integer getIdReservacion() {
        return this.idReservacion;
    }
    
    public void setIdReservacion(Integer idReservacion) {
        this.idReservacion = idReservacion;
    }
    public int getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(int idCliente) {
        this.idCliente = idCliente;
    }




}


