package org.hibernate.model;
// Generated 21/08/2012 05:48:10 PM by Hibernate Tools 3.2.1.GA



/**
 * Vuelos generated by hbm2java
 */
public class Vuelos  implements java.io.Serializable {


     private Integer idVuelo;
     private String ciudadOrigen;
     private String ciudadDestino;
     private String horaSalida;
     private String horaLlegada;
     private int idAvion;
     private int idReservacion;
     private double preciosNinos;
     private double precioAdultos;

    public Vuelos() {
    }

    public Vuelos(String ciudadOrigen, String ciudadDestino, String horaSalida, String horaLlegada, int idAvion, int idReservacion, double preciosNinos, double precioAdultos) {
       this.ciudadOrigen = ciudadOrigen;
       this.ciudadDestino = ciudadDestino;
       this.horaSalida = horaSalida;
       this.horaLlegada = horaLlegada;
       this.idAvion = idAvion;
       this.idReservacion = idReservacion;
       this.preciosNinos = preciosNinos;
       this.precioAdultos = precioAdultos;
    }
   
    public Integer getIdVuelo() {
        return this.idVuelo;
    }
    
    public void setIdVuelo(Integer idVuelo) {
        this.idVuelo = idVuelo;
    }
    public String getCiudadOrigen() {
        return this.ciudadOrigen;
    }
    
    public void setCiudadOrigen(String ciudadOrigen) {
        this.ciudadOrigen = ciudadOrigen;
    }
    public String getCiudadDestino() {
        return this.ciudadDestino;
    }
    
    public void setCiudadDestino(String ciudadDestino) {
        this.ciudadDestino = ciudadDestino;
    }
    public String getHoraSalida() {
        return this.horaSalida;
    }
    
    public void setHoraSalida(String horaSalida) {
        this.horaSalida = horaSalida;
    }
    public String getHoraLlegada() {
        return this.horaLlegada;
    }
    
    public void setHoraLlegada(String horaLlegada) {
        this.horaLlegada = horaLlegada;
    }
    public int getIdAvion() {
        return this.idAvion;
    }
    
    public void setIdAvion(int idAvion) {
        this.idAvion = idAvion;
    }
    public int getIdReservacion() {
        return this.idReservacion;
    }
    
    public void setIdReservacion(int idReservacion) {
        this.idReservacion = idReservacion;
    }
    public double getPreciosNinos() {
        return this.preciosNinos;
    }
    
    public void setPreciosNinos(double preciosNinos) {
        this.preciosNinos = preciosNinos;
    }
    public double getPrecioAdultos() {
        return this.precioAdultos;
    }
    
    public void setPrecioAdultos(double precioAdultos) {
        this.precioAdultos = precioAdultos;
    }




}


